<p>Write a <code>retry</code> decorator that retries executing the function it decorates.&nbsp;If the function raises an exception (any kind) it tries again, until it reaches <code>MAX_RETRIES</code> (set to 3) at which point it throws a <code>MaxRetriesException</code> exception (already defined).</p>
<p>In the tests we define <code>get_two_numbers</code> to test this. It gets a list of numbers which may contain bad data (non <code>int</code>s or <code>float</code>s). It tries to pick 2 random numbers from this list but if both those numbers are not <code>int</code>s, it raises a <code>ValueError</code> in which case the retry decorator would run the function again.</p>
<p>Check out the template's docstring as well as the tests for more details. Good luck and keep calm and code in Python!</p>